-- MySQL Script generated by MySQL Workbench
-- Sun Sep  4 09:56:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Lerntool
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Lerntool` ;

-- -----------------------------------------------------
-- Schema Lerntool
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Lerntool` DEFAULT CHARACTER SET utf8 ;
USE `Lerntool` ;

-- -----------------------------------------------------
-- Table `Lerntool`.`gruppe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lerntool`.`gruppe` ;

CREATE TABLE IF NOT EXISTS `Lerntool`.`gruppe` (
  `gruppeNr` VARCHAR(20) NOT NULL,
  `ausbildungName` VARCHAR(45) NULL,
  PRIMARY KEY (`gruppeNr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lerntool`.`benutzer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lerntool`.`benutzer` ;

CREATE TABLE IF NOT EXISTS `Lerntool`.`benutzer` (
  `uid` VARCHAR(20) NOT NULL,
  `anzeigename` VARCHAR(40) NULL,
  `passwort` VARCHAR(255) NULL,
  `gruppe` VARCHAR(20) NULL,
  `type` ENUM('user', 'admin') NOT NULL,
  PRIMARY KEY (`uid`),
  INDEX `gruppe_idx` (`gruppe` ASC) VISIBLE,
  CONSTRAINT `gruppe`
    FOREIGN KEY (`gruppe`)
    REFERENCES `Lerntool`.`gruppe` (`gruppeNr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lerntool`.`faecher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lerntool`.`faecher` ;

CREATE TABLE IF NOT EXISTS `Lerntool`.`faecher` (
  `fach_id` INT NOT NULL AUTO_INCREMENT,
  `anzeigename` VARCHAR(45) NULL,
  PRIMARY KEY (`fach_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lerntool`.`themen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lerntool`.`themen` ;

CREATE TABLE IF NOT EXISTS `Lerntool`.`themen` (
  `thema_id` INT NOT NULL AUTO_INCREMENT,
  `anzeigename` VARCHAR(80) NULL,
  `fach_id` INT NOT NULL,
  PRIMARY KEY (`thema_id`),
  INDEX `fach_id_idx` (`fach_id` ASC) VISIBLE,
  CONSTRAINT `fach_id`
    FOREIGN KEY (`fach_id`)
    REFERENCES `Lerntool`.`faecher` (`fach_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lerntool`.`fragen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lerntool`.`fragen` ;

CREATE TABLE IF NOT EXISTS `Lerntool`.`fragen` (
  `frage_id` INT NOT NULL AUTO_INCREMENT,
  `fragenText` LONGTEXT NULL,
  `fragenTyp` ENUM('MultipleChoiceSelect', 'MultipleChoiceCheck', 'SingleChoice', 'TextEingabe') NULL,
  `thema_id` INT NOT NULL,
  PRIMARY KEY (`frage_id`),
  INDEX `fk_fragen_faecher_idx` (`thema_id` ASC) VISIBLE,
  CONSTRAINT `fk_fragen_faecher`
    FOREIGN KEY (`thema_id`)
    REFERENCES `Lerntool`.`themen` (`thema_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lerntool`.`benutzer_fragen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lerntool`.`benutzer_fragen` ;

CREATE TABLE IF NOT EXISTS `Lerntool`.`benutzer_fragen` (
  `benutzer_uid` VARCHAR(20) NOT NULL,
  `frage_id` INT NOT NULL,
  `richtig` INT NOT NULL DEFAULT 0,
  `falsch` INT NOT NULL DEFAULT 0,
  `abgefragt` INT NOT NULL DEFAULT 1,
  INDEX `uid_idx` (`benutzer_uid` ASC) VISIBLE,
  INDEX `frage_id_idx` (`frage_id` ASC) VISIBLE,
  PRIMARY KEY (`benutzer_uid`, `frage_id`),
  CONSTRAINT `benutzerfrage_uid`
    FOREIGN KEY (`benutzer_uid`)
    REFERENCES `Lerntool`.`benutzer` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `benutzerfrage_frage_id`
    FOREIGN KEY (`frage_id`)
    REFERENCES `Lerntool`.`fragen` (`frage_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lerntool`.`antworten`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lerntool`.`antworten` ;

CREATE TABLE IF NOT EXISTS `Lerntool`.`antworten` (
  `antwort_id` INT NOT NULL AUTO_INCREMENT,
  `antwortText` VARCHAR(255) NULL,
  `fragen_id` INT NOT NULL,
  `istRichtig` TINYINT NOT NULL,
  PRIMARY KEY (`antwort_id`),
  INDEX `fragen_id_idx` (`fragen_id` ASC) VISIBLE,
  CONSTRAINT `fragen_id`
    FOREIGN KEY (`fragen_id`)
    REFERENCES `Lerntool`.`fragen` (`frage_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lerntool`.`benutzer_themen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lerntool`.`benutzer_themen` ;

CREATE TABLE IF NOT EXISTS `Lerntool`.`benutzer_themen` (
  `benutzerthemen_gruppe` VARCHAR(20) NOT NULL,
  `benutzerthemen_thema_id` INT NOT NULL,
  INDEX `benutzerfaecher_thema_id_idx` (`benutzerthemen_thema_id` ASC) VISIBLE,
  CONSTRAINT `benutzerfaecher_gruppe`
    FOREIGN KEY (`benutzerthemen_gruppe`)
    REFERENCES `Lerntool`.`gruppe` (`gruppeNr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `benutzerfaecher_thema_id`
    FOREIGN KEY (`benutzerthemen_thema_id`)
    REFERENCES `Lerntool`.`themen` (`thema_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
